# app/config/security.yml
security:
   encoders:
       innoLCL\AllUserBundle\Entity\User: sha512

   role_hierarchy:
       ROLE_ADMIN:       [ROLE_MODERATEUR,ROLE_LECTEUR,ROLE_VALIDATEUR,ROLE_SELECTIONNEUR]
       ROLE_PARTICIPANT: ROLE_USER

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username_email

   firewalls:
   # firewall du FrontOffice
    front_secured_area:
        pattern: ^/
        form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
            login_path: /
            check_path: fos_user_security_check
            default_target_path: innoLCL_alluserbundle_redirect 
        logout:
            path:        /logout
            target:      /
            success_handler: redirect.after.logout
        anonymous:       true
        
    #firewalls du Backoffice            NON FONCTIONNEL
    admin_secured_area:
        pattern: ^/admin
        form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
            login_path: fos_admin_user_security_login
            check_path: fos_admin_user_security_check
            default_target_path: innoLCL_alluserbundle_redirect             
        logout:
            path: fos_admin_user_security_logout
            target: fos_admin_user_security_login            
        anonymous: true




   access_control:
       #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       
       
       
       #- { path: ^/admin/, role: ROLE_ADMIN }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/moderateur, role: ROLE_MODERATEUR }
       - { path: ^/admin/lecteur, role: ROLE_LECTEUR }
       - { path: ^/admin/validateur, role: ROLE_VALIDATEUR }
       - { path: ^/admin/selectionneur, role: ROLE_SELECTIONNEUR }
       
       - { path: ^/proposal$, role: ROLE_USER }
       - { path: ^/handleFrontForm, role: ROLE_USER }

