<?php

namespace innoLCL\AllUserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * Donne le nombre d'idée selectionnée
    *
    * @param none
    * @return int
    */
    public function getAllWithResetToken() 
    {
        $today = new \DateTime();
        $today->modify('-1 hour');
        $todayCompare = $today->format('Y-m-d H:i:s');
        
        $qb = $this->createQueryBuilder('u');
        $qb->select('u')
                ->where($qb->expr()->isNotNull('u.confirmationToken'))
                ->andWhere('u.passwordRequestedAt <= :todayCompare');
        
        $qb->setParameter('todayCompare', $todayCompare);
        return $qb->getQuery()->getResult();
    }
}
